language: node_js
node_js:
  - '8'
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - frontend/node_modules
    - backend/node_modules

script:
  - cd frontend
  - npm install
  - npm run build
  - cd ../backend
  - npm install
  - npm run start

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: code-editor-api
